## NumPy arrays

### Creating a numpy array from the python object such as a list

In [36]:
first_array = [1,2,3]

In [37]:
import numpy as np

In [38]:
array = np.array(first_array)

In [39]:
array

array([1, 2, 3])

### Creating a matrix using the NumPy array

In [40]:
first_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [41]:
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### If we are creating an array using the NumPy array they will be much faster then using the list from Python

##### Creating the numpy array from some range of numbers

In [42]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Creating the numpy array using the arange function and even numbers (passing the set size as third argument)

In [43]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Creating an array with just zeroes as elements

In [44]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones((1,7))

array([[1., 1., 1., 1., 1., 1., 1.]])

In [47]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Creating the array from 0 to 5 by splitting it on 10 parts

In [48]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### Creating the unit matrix

In [50]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating the array of random numbers

#### Returning numbers from the uniform distribution

In [51]:
np.random.rand(5)

array([0.75410278, 0.4560086 , 0.39521993, 0.02551729, 0.84342321])

In [52]:
np.random.rand(5,2)


array([[0.85364649, 0.55275494],
       [0.62033443, 0.31423505],
       [0.70203086, 0.09881782],
       [0.79913812, 0.48612439],
       [0.23954678, 0.99915555]])

#### Returning numbers that are not from uniform distribution, but they are part of standard normal distribution

In [56]:
np.random.randn(2)

array([-0.5013856 ,  0.51147464])

In [57]:
np.random.randn(2,2)

array([[ 0.63392433,  1.04134713],
       [ 0.8264213 , -0.70454272]])

#### Creating the array just of random numbers

In [62]:
np.random.randint(1,100,10) #third parameter is number of numbers that we want

array([11, 60, 39,  9, 50, 25, 99, 56, 12, 94])