# NumPy arrays

## Creating a numpy array from the python object such as a list

In [835]:
first_array = [1,2,3]

In [836]:
import numpy as np

In [837]:
array = np.array(first_array)

In [838]:
array

array([1, 2, 3])

### Creating a matrix using the NumPy array

In [839]:
first_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [840]:
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### If we are creating an array using the NumPy array they will be much faster then using the list from Python

##### Creating the numpy array from some range of numbers

In [841]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Creating the numpy array using the arange function and even numbers (passing the set size as third argument)

In [842]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Creating an array with just zeroes as elements

In [843]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [844]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [845]:
np.ones((1,7))

array([[1., 1., 1., 1., 1., 1., 1.]])

In [846]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Creating the array from 0 to 5 by splitting it on 10 parts

In [847]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### Creating the unit matrix

In [848]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating the array of random numbers

#### Returning numbers from the uniform distribution

In [849]:
np.random.rand(5)

array([0.93460405, 0.60463334, 0.08487412, 0.49050462, 0.25335239])

In [850]:
np.random.rand(5,2)


array([[0.96133727, 0.68794061],
       [0.75396773, 0.47501289],
       [0.71673197, 0.18882521],
       [0.4305592 , 0.92708712],
       [0.29191643, 0.17344438]])

#### Returning numbers that are not from uniform distribution, but they are part of standard normal distribution

In [851]:
np.random.randn(2)

array([-0.55408054, -0.16180174])

In [852]:
np.random.randn(2,2)

array([[ 0.18649721, -0.48372317],
       [-0.04599233,  1.32492104]])

#### Creating the array just of random numbers

In [853]:
np.random.randint(1,100,10) #third parameter is number of numbers that we want

array([58,  7, 19, 25, 52, 53, 18, 40, 90, 22])

In [854]:
arr = np.arange(25)

In [855]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [856]:
random_array = np.random.randint(0,50,10)

In [857]:
random_array

array([ 6, 29, 13, 14, 22, 19, 32, 37,  9, 40])

#### Changing the shape of existing array

In [858]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### Finding the maximum value in the array

In [859]:
random_array.max()

40

##### Finding the minimum value in the array

In [860]:
random_array.min()

6

##### Finding the index of maximum value

In [861]:
random_array.argmax()

9

##### Finding the index of minimum value

In [862]:
random_array.argmin()

0

##### Finding the shape of any array

In [863]:
random_array.shape #if we got e.g. (10,) it's referencing to the one dimensional array

(10,)

In [864]:
random_array = random_array.reshape(5,2)

In [865]:
random_array.shape

(5, 2)

In [866]:
random_array

array([[ 6, 29],
       [13, 14],
       [22, 19],
       [32, 37],
       [ 9, 40]])

##### Getting the data type of the array

In [867]:
random_array.dtype

dtype('int64')

In [868]:
from numpy.random import randint

In [869]:
randint(5,100)

40

## NumPy array indexing and selection

In [870]:
new_array = np.arange(0,11)

In [871]:
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [872]:
new_array[6]

6

In [873]:
new_array[:] #this means get all elements

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [874]:
new_array[1:5] 

array([1, 2, 3, 4])

In [875]:
new_array[6:]

array([ 6,  7,  8,  9, 10])

In [876]:
new_array[:6]

array([0, 1, 2, 3, 4, 5])

In [877]:
new_array[0:5] = 100 #overriding the elements

In [878]:
new_array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [879]:
slice_of_array = new_array[0:6]

In [880]:
slice_of_array

array([100, 100, 100, 100, 100,   5])

In [881]:
slice_of_array[:]=99 #this also will override elements in the new_array

In [882]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [883]:
new_array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [884]:
splice_arr = new_array.copy()

In [885]:
splice_arr[:] = 99

In [886]:
splice_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [887]:
new_array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing of the matrix (2D array)

In [888]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [889]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [890]:
matrix[2][2]

45

In [891]:
matrix[0]

array([ 5, 10, 15])

In [892]:
matrix[2,1] #this will also grab an element on position [2][1] in the matrix

40

In [893]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [894]:
matrix[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

#### Condition selection

In [895]:
array_1 = np.arange(1,11)

In [896]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [897]:
array_1 > 5 #compare all elements in the array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [898]:
bool_array = array_1 > 5

In [899]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [900]:
array_1[bool_array] #returns only elements on places when in boolean array element is equal to true

array([ 6,  7,  8,  9, 10])

In [901]:
array_1[array_1>5]

array([ 6,  7,  8,  9, 10])

In [902]:
array_1[array_1<3]

array([1, 2])

In [903]:
array_2d = np.arange(50).reshape(5,10)

In [904]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [905]:
array_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])