## NumPy arrays

### Creating a numpy array from the python object such as a list

In [222]:
first_array = [1,2,3]

In [223]:
import numpy as np

In [224]:
array = np.array(first_array)

In [225]:
array

array([1, 2, 3])

### Creating a matrix using the NumPy array

In [226]:
first_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [227]:
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### If we are creating an array using the NumPy array they will be much faster then using the list from Python

##### Creating the numpy array from some range of numbers

In [228]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Creating the numpy array using the arange function and even numbers (passing the set size as third argument)

In [229]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Creating an array with just zeroes as elements

In [230]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [231]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [232]:
np.ones((1,7))

array([[1., 1., 1., 1., 1., 1., 1.]])

In [233]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Creating the array from 0 to 5 by splitting it on 10 parts

In [234]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### Creating the unit matrix

In [235]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating the array of random numbers

#### Returning numbers from the uniform distribution

In [236]:
np.random.rand(5)

array([0.94189749, 0.76722638, 0.01834357, 0.74835787, 0.48100129])

In [237]:
np.random.rand(5,2)


array([[0.14064976, 0.10727398],
       [0.94864633, 0.42099102],
       [0.15449865, 0.17348659],
       [0.15465901, 0.33903046],
       [0.90431297, 0.2539128 ]])

#### Returning numbers that are not from uniform distribution, but they are part of standard normal distribution

In [238]:
np.random.randn(2)

array([-0.28140652,  0.9476571 ])

In [239]:
np.random.randn(2,2)

array([[-0.51114817, -0.14385512],
       [ 0.59295649,  0.83474332]])

#### Creating the array just of random numbers

In [240]:
np.random.randint(1,100,10) #third parameter is number of numbers that we want

array([83, 76, 88, 93, 92, 16, 22, 55, 15, 59])

In [241]:
arr = np.arange(25)

In [242]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [243]:
random_array = np.random.randint(0,50,10)

In [244]:
random_array

array([38, 44,  0, 38, 13, 20,  3, 22,  7, 33])

#### Changing the shape of existing array

In [245]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### Finding the maximum value in the array

In [246]:
random_array.max()

44

##### Finding the minimum value in the array

In [247]:
random_array.min()

0

##### Finding the index of maximum value

In [248]:
random_array.argmax()

1

##### Finding the index of minimum value

In [249]:
random_array.argmin()

2

##### Finding the shape of any array

In [250]:
random_array.shape #if we got e.g. (10,) it's referencing to the one dimensional array

(10,)

In [251]:
random_array = random_array.reshape(5,2)

In [252]:
random_array.shape

(5, 2)

In [253]:
random_array

array([[38, 44],
       [ 0, 38],
       [13, 20],
       [ 3, 22],
       [ 7, 33]])

##### Getting the data type of the array

In [254]:
random_array.dtype

dtype('int64')