# NumPy arrays

## Creating a numpy array from the python object such as a list

In [499]:
first_array = [1,2,3]

In [500]:
import numpy as np

In [501]:
array = np.array(first_array)

In [502]:
array

array([1, 2, 3])

### Creating a matrix using the NumPy array

In [503]:
first_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [504]:
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### If we are creating an array using the NumPy array they will be much faster then using the list from Python

##### Creating the numpy array from some range of numbers

In [505]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Creating the numpy array using the arange function and even numbers (passing the set size as third argument)

In [506]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Creating an array with just zeroes as elements

In [507]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [508]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [509]:
np.ones((1,7))

array([[1., 1., 1., 1., 1., 1., 1.]])

In [510]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Creating the array from 0 to 5 by splitting it on 10 parts

In [511]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### Creating the unit matrix

In [512]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating the array of random numbers

#### Returning numbers from the uniform distribution

In [513]:
np.random.rand(5)

array([0.58586133, 0.34604094, 0.53802215, 0.82804448, 0.45294992])

In [514]:
np.random.rand(5,2)


array([[0.57143126, 0.17317604],
       [0.83692345, 0.00095881],
       [0.45981744, 0.58717693],
       [0.14868915, 0.39180996],
       [0.80473685, 0.39070841]])

#### Returning numbers that are not from uniform distribution, but they are part of standard normal distribution

In [515]:
np.random.randn(2)

array([ 0.35813636, -0.05035549])

In [516]:
np.random.randn(2,2)

array([[ 1.28221497, -0.30869481],
       [ 0.70079886,  0.11600203]])

#### Creating the array just of random numbers

In [517]:
np.random.randint(1,100,10) #third parameter is number of numbers that we want

array([98, 12, 70, 65, 44, 91, 10, 69, 87, 33])

In [518]:
arr = np.arange(25)

In [519]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [520]:
random_array = np.random.randint(0,50,10)

In [521]:
random_array

array([12, 45, 17,  0, 40, 39, 35, 16, 25, 18])

#### Changing the shape of existing array

In [522]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### Finding the maximum value in the array

In [523]:
random_array.max()

45

##### Finding the minimum value in the array

In [524]:
random_array.min()

0

##### Finding the index of maximum value

In [525]:
random_array.argmax()

1

##### Finding the index of minimum value

In [526]:
random_array.argmin()

3

##### Finding the shape of any array

In [527]:
random_array.shape #if we got e.g. (10,) it's referencing to the one dimensional array

(10,)

In [528]:
random_array = random_array.reshape(5,2)

In [529]:
random_array.shape

(5, 2)

In [530]:
random_array

array([[12, 45],
       [17,  0],
       [40, 39],
       [35, 16],
       [25, 18]])

##### Getting the data type of the array

In [531]:
random_array.dtype

dtype('int64')

In [532]:
from numpy.random import randint

In [533]:
randint(5,100)

41

## NumPy array indexing and selection

In [534]:
new_array = np.arange(0,11)

In [535]:
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [536]:
new_array[6]

6

In [537]:
new_array[:] #this means get all elements

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [538]:
new_array[1:5] 

array([1, 2, 3, 4])

In [539]:
new_array[6:]

array([ 6,  7,  8,  9, 10])

In [540]:
new_array[:6]

array([0, 1, 2, 3, 4, 5])

In [541]:
new_array[0:5] = 100 #overriding the elements

In [542]:
new_array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [543]:
slice_of_array = new_array[0:6]

In [544]:
slice_of_array

array([100, 100, 100, 100, 100,   5])

In [545]:
slice_of_array[:]=99 #this also will override elements in the new_array

In [546]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [547]:
new_array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [548]:
splice_arr = new_array.copy()

In [549]:
splice_arr[:] = 99

In [550]:
splice_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [551]:
new_array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])