# NumPy arrays

## Creating a numpy array from the python object such as a list

In [925]:
first_array = [1,2,3]

In [926]:
import numpy as np

In [927]:
array = np.array(first_array)

In [928]:
array

array([1, 2, 3])

### Creating a matrix using the NumPy array

In [929]:
first_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [930]:
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### If we are creating an array using the NumPy array they will be much faster then using the list from Python

##### Creating the numpy array from some range of numbers

In [931]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Creating the numpy array using the arange function and even numbers (passing the set size as third argument)

In [932]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Creating an array with just zeroes as elements

In [933]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [934]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [935]:
np.ones((1,7))

array([[1., 1., 1., 1., 1., 1., 1.]])

In [936]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Creating the array from 0 to 5 by splitting it on 10 parts

In [937]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### Creating the unit matrix

In [938]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating the array of random numbers

#### Returning numbers from the uniform distribution

In [939]:
np.random.rand(5)

array([0.28848898, 0.59796378, 0.81509208, 0.82849513, 0.61655701])

In [940]:
np.random.rand(5,2)


array([[0.78821991, 0.75359984],
       [0.28992862, 0.8402884 ],
       [0.55484365, 0.66172134],
       [0.98016179, 0.21148649],
       [0.86593144, 0.31560023]])

#### Returning numbers that are not from uniform distribution, but they are part of standard normal distribution

In [941]:
np.random.randn(2)

array([-0.50677666, -0.33960314])

In [942]:
np.random.randn(2,2)

array([[ 0.04966574, -0.12005538],
       [ 0.2608339 ,  1.41701567]])

#### Creating the array just of random numbers

In [943]:
np.random.randint(1,100,10) #third parameter is number of numbers that we want

array([82, 31,  9, 38, 90, 67, 23, 36, 95, 65])

In [944]:
arr = np.arange(25)

In [945]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [946]:
random_array = np.random.randint(0,50,10)

In [947]:
random_array

array([40,  5, 29,  9, 11, 14, 45, 42,  9, 24])

#### Changing the shape of existing array

In [948]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### Finding the maximum value in the array

In [949]:
random_array.max()

45

##### Finding the minimum value in the array

In [950]:
random_array.min()

5

##### Finding the index of maximum value

In [951]:
random_array.argmax()

6

##### Finding the index of minimum value

In [952]:
random_array.argmin()

1

##### Finding the shape of any array

In [953]:
random_array.shape #if we got e.g. (10,) it's referencing to the one dimensional array

(10,)

In [954]:
random_array = random_array.reshape(5,2)

In [955]:
random_array.shape

(5, 2)

In [956]:
random_array

array([[40,  5],
       [29,  9],
       [11, 14],
       [45, 42],
       [ 9, 24]])

##### Getting the data type of the array

In [957]:
random_array.dtype

dtype('int64')

In [958]:
from numpy.random import randint

In [959]:
randint(5,100)

31

## NumPy array indexing and selection

In [960]:
new_array = np.arange(0,11)

In [961]:
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [962]:
new_array[6]

6

In [963]:
new_array[:] #this means get all elements

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [964]:
new_array[1:5] 

array([1, 2, 3, 4])

In [965]:
new_array[6:]

array([ 6,  7,  8,  9, 10])

In [966]:
new_array[:6]

array([0, 1, 2, 3, 4, 5])

In [967]:
new_array[0:5] = 100 #overriding the elements

In [968]:
new_array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [969]:
slice_of_array = new_array[0:6]

In [970]:
slice_of_array

array([100, 100, 100, 100, 100,   5])

In [971]:
slice_of_array[:]=99 #this also will override elements in the new_array

In [972]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [973]:
new_array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [974]:
splice_arr = new_array.copy()

In [975]:
splice_arr[:] = 99

In [976]:
splice_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [977]:
new_array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing of the matrix (2D array)

In [978]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [979]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [980]:
matrix[2][2]

45

In [981]:
matrix[0]

array([ 5, 10, 15])

In [982]:
matrix[2,1] #this will also grab an element on position [2][1] in the matrix

40

In [983]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [984]:
matrix[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

#### Condition selection

In [985]:
array_1 = np.arange(1,11)

In [986]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [987]:
array_1 > 5 #compare all elements in the array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [988]:
bool_array = array_1 > 5

In [989]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [990]:
array_1[bool_array] #returns only elements on places when in boolean array element is equal to true

array([ 6,  7,  8,  9, 10])

In [991]:
array_1[array_1>5]

array([ 6,  7,  8,  9, 10])

In [992]:
array_1[array_1<3]

array([1, 2])

In [993]:
array_2d = np.arange(50).reshape(5,10)

In [994]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [995]:
array_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## NumPy operations

- array with array operations
- array with scalers operations
- universal array functions 

In [996]:
new_arr = np.arange(0,11)

In [997]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [998]:
new_arr + new_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [999]:
new_arr - new_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [1000]:
new_arr * new_arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [1001]:
new_arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [1002]:
new_arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [1003]:
new_arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [1004]:
np.sqrt(new_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [1005]:
np.exp(new_arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [1006]:
np.max(new_arr)

10

In [1007]:
np.sin(new_arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [1008]:
np.tan(new_arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [1009]:
np.log(new_arr)

/var/folders/5j/h8jcn7rx63n551f1642_r1p80000gn/T/ipykernel_29986/4032041029.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(new_arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])