## NumPy arrays

### Creating a numpy array from the python object such as a list

In [258]:
first_array = [1,2,3]

In [259]:
import numpy as np

In [260]:
array = np.array(first_array)

In [261]:
array

array([1, 2, 3])

### Creating a matrix using the NumPy array

In [262]:
first_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [263]:
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### If we are creating an array using the NumPy array they will be much faster then using the list from Python

##### Creating the numpy array from some range of numbers

In [264]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Creating the numpy array using the arange function and even numbers (passing the set size as third argument)

In [265]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Creating an array with just zeroes as elements

In [266]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [267]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [268]:
np.ones((1,7))

array([[1., 1., 1., 1., 1., 1., 1.]])

In [269]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Creating the array from 0 to 5 by splitting it on 10 parts

In [270]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### Creating the unit matrix

In [271]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating the array of random numbers

#### Returning numbers from the uniform distribution

In [272]:
np.random.rand(5)

array([0.48184012, 0.19843097, 0.64939561, 0.58072188, 0.0493207 ])

In [273]:
np.random.rand(5,2)


array([[0.84786993, 0.06620851],
       [0.87270333, 0.40397892],
       [0.3008552 , 0.6541006 ],
       [0.11075495, 0.5990879 ],
       [0.69817407, 0.61639579]])

#### Returning numbers that are not from uniform distribution, but they are part of standard normal distribution

In [274]:
np.random.randn(2)

array([0.79762764, 0.2301499 ])

In [275]:
np.random.randn(2,2)

array([[-0.40111569,  2.1032973 ],
       [ 0.90496781, -0.59479028]])

#### Creating the array just of random numbers

In [276]:
np.random.randint(1,100,10) #third parameter is number of numbers that we want

array([71, 48, 60, 62, 32, 24, 33, 72, 72, 33])

In [277]:
arr = np.arange(25)

In [278]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [279]:
random_array = np.random.randint(0,50,10)

In [280]:
random_array

array([41, 40, 11, 14,  6,  5, 39, 46, 38, 44])

#### Changing the shape of existing array

In [281]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### Finding the maximum value in the array

In [282]:
random_array.max()

46

##### Finding the minimum value in the array

In [283]:
random_array.min()

5

##### Finding the index of maximum value

In [284]:
random_array.argmax()

7

##### Finding the index of minimum value

In [285]:
random_array.argmin()

5

##### Finding the shape of any array

In [286]:
random_array.shape #if we got e.g. (10,) it's referencing to the one dimensional array

(10,)

In [287]:
random_array = random_array.reshape(5,2)

In [288]:
random_array.shape

(5, 2)

In [289]:
random_array

array([[41, 40],
       [11, 14],
       [ 6,  5],
       [39, 46],
       [38, 44]])

##### Getting the data type of the array

In [290]:
random_array.dtype

dtype('int64')

In [291]:
from numpy.random import randint

In [292]:
randint(5,100)

63