## NumPy arrays

### Creating a numpy array from the python object such as a list

In [2]:
first_array = [1,2,3]

In [4]:
import numpy as np

In [6]:
array = np.array(first_array)

In [7]:
array

array([1, 2, 3])

### Creating a matrix using the NumPy array

In [9]:
first_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### If we are creating an array using the NumPy array they will be much faster then using the list from Python

##### Creating the numpy array from some range of numbers

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Creating the numpy array using the arange function and even numbers (passing the set size as third argument)

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Creating an array with just zeroes as elements

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((1,7))

array([[1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])