## NumPy arrays

### Creating a numpy array from the python object such as a list

In [63]:
first_array = [1,2,3]

In [64]:
import numpy as np

In [65]:
array = np.array(first_array)

In [66]:
array

array([1, 2, 3])

### Creating a matrix using the NumPy array

In [67]:
first_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [68]:
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### If we are creating an array using the NumPy array they will be much faster then using the list from Python

##### Creating the numpy array from some range of numbers

In [69]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Creating the numpy array using the arange function and even numbers (passing the set size as third argument)

In [70]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##### Creating an array with just zeroes as elements

In [71]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
np.ones((1,7))

array([[1., 1., 1., 1., 1., 1., 1.]])

In [74]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Creating the array from 0 to 5 by splitting it on 10 parts

In [75]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### Creating the unit matrix

In [76]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating the array of random numbers

#### Returning numbers from the uniform distribution

In [77]:
np.random.rand(5)

array([0.0904029 , 0.97957096, 0.53924566, 0.18500645, 0.05725798])

In [78]:
np.random.rand(5,2)


array([[0.27447685, 0.99923269],
       [0.01168103, 0.57030545],
       [0.5848439 , 0.51056501],
       [0.55838635, 0.84628099],
       [0.2921552 , 0.15034396]])

#### Returning numbers that are not from uniform distribution, but they are part of standard normal distribution

In [79]:
np.random.randn(2)

array([-0.74429163, -1.63605836])

In [80]:
np.random.randn(2,2)

array([[ 0.2538151 ,  0.56497051],
       [ 1.05483804, -0.18793305]])

#### Creating the array just of random numbers

In [81]:
np.random.randint(1,100,10) #third parameter is number of numbers that we want

array([ 2, 75, 32, 32, 18, 40, 63,  6, 71, 44])