# NumPy Exercises

## import numpy library as np

In [35]:
import numpy as np

## Create an array of 10 zeros

In [36]:
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create the array of 10 ones

In [37]:
array_ones = np.ones(10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create an array of 10 fives

In [38]:
array_fives = np.array(5)

In [39]:
array_fives

array(5)

## Create an array of the integers from 10 to 50

In [40]:
array_range = np.arange(10,50)

In [41]:
array_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Create an array of all even numbers integers from 10 to 50

In [42]:
even_array = np.arange(10,50,2)

In [43]:
even_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

## Create a 3x3 matrix with values ranging from 0 to 8

In [44]:
matrix = np.arange(0,9)
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Create a 3x3 identity matrix

In [45]:
identity_matrix=np.eye(3)

In [46]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Use numpy to generate a random number between 0 and 1

In [47]:
np.random.random(1)

array([0.74868225])

## Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution


In [48]:
np.random.randn(25)

array([-0.13533042,  0.59902326,  0.64947902,  0.6143006 , -0.30355404,
        2.2199935 , -0.95340914, -1.17635018,  1.0668352 ,  0.16305463,
       -0.08635585,  1.10809729,  1.72761065,  0.9234586 ,  0.93581069,
        0.99214376,  1.96611132,  0.12101731,  0.55054569, -0.30596035,
       -0.51425212,  0.64206864, -0.21557874, -1.76243985, -0.90811168])